services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alxsignals-test
    # command: pytest
    command: >
      sh -c "python manage.py makemigrations messaging --noinput &&
             python manage.py test messaging.tests.NotificationSignalTest -v 2 &&
             python manage.py test messaging.tests.MessageEditSignalTest -v 2 &&
             python manage.py test messaging.tests.DeleteUserSignalTest -v 2 
      "
    env_file:
      - .env.test   # separate env file for test credentials
    environment:
      MYSQL_DATABASE: test_alxsignals
      MYSQL_USER: testuser
      MYSQL_PASSWORD: strongpassword
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    volumes:
      - ./messaging_app:/app/messaging_app
      - ./chats:/app/chats
      - ./messaging:/app/messaging
      - ./manage.py:/app/manage.py
      - ./requests.log:/app/requests.log   # âœ… mount only requests.log
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: alxsignals-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - as_test_db_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"   # avoid clashing with dev DB
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  as_test_db_data: