name: Messaging App CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_call:   # makes this workflow reusable

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: messaging_app/messaging_app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use CI env file
        run: cp ../../.github/workflows/.env.ci .env

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yaml up -d db rabbitmq
          # Wait for MySQL to be healthy
          until docker exec alxmessaging-mysql mysqladmin ping -h 127.0.0.1 -uroot -p${MYSQL_ROOT_PASSWORD} --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Run tests inside web service
        run: |
          # Override the web service command to run pytest instead of Gunicorn
          docker compose run --rm web pytest --ds=messaging_app.settings --junitxml=reports/test-results.xml

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.yaml down -v